### ISSUE TITLE
Binary data + mbstring.func_overload = boom

### ISSUE THREAD

**Issue by paragonie-scott** [zendframework/zend-crypt#20]
`php -dmbstring.func_overload=7 test.php`

``` php
<?php
var_dump(strlen("\xF0\x9D\xA5\xB3"));
// int(1)
```

Using `strlen()` and `substr()` for crypto can be dangerous, especially since you work with raw binary.

**Comment by Ocramius** [comment]
Could you please reference locations in the codebase using this? Could be useful to see where it needs to be removed.

**Comment by paragonie-scott** [comment]
One specific place where it operates on user input:
- https://github.com/zendframework/zend-crypt/blob/625f8d5c648ab6ef3e595bd4a99d832f09f4e307/src/Symmetric/Mcrypt.php#L384-L385

Generally:
- https://github.com/zendframework/zend-crypt/search?utf8=%E2%9C%93&q=substr
- https://github.com/zendframework/zend-crypt/search?utf8=%E2%9C%93&q=strlen

**Comment by paragonie-scott** [comment]
Also, more critically:
- https://github.com/zendframework/zend-crypt/blob/625f8d5c648ab6ef3e595bd4a99d832f09f4e307/src/Utils.php#L39-L40

PHP < 5.5 could, with `mbstring.func_overload`, be more susceptible to chosen-ciphertext attacks via MAC forgery, provided the calculated MAC for a forged message and the forged MAC sent by the attacker both conforms to 8 x 4-byte UTF8 characters.

**Comment by Ocramius** [comment]
@paragonie-scott thanks :-)

**Comment by paragonie-scott** [comment]
Also, should #21 be merged:

https://github.com/paragonie/constant_time_encoding/blob/master/src/Core.php

**Comment by ezimuel** [comment]
@paragonie-scott regarding #21 I just closed it, we will consider it for the future, not at the moment. Thanks.

**Comment by ezimuel** [comment]
@paragonie-scott I just sent the PR #22 that removes the usage of substr() and strlen() in favor of mb_\* functions. /cc @Ocramius
