### ISSUE TITLE
Please consider to deprecate MCrypt usage

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-crypt#3]
Zend\Crypt\Symmetric\MCrypt rely on libmcrypt and php-mcrypt/

Libmcrypt is a dead cow, unmaintained for ~8 year, rely on such things can't be serious.

I understand it is not easy to drop such feature, especially for applications using ZF2, but probably it could be possible to deprecate this class, to encourage user to switch to something else, and to be able to drop it later.

**Comment by remicollet** [comment]
A just wrote a summary about this, see http://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt

**Comment by Ocramius** [comment]
This can most probably be done for `zend-crypt` `3.x`

**Comment by gianarb** [comment]
Yes.. We can maintain this feature into the 2.\* and we remove it to 3.*

**Comment by ezimuel** [comment]
@remicollet I know that libmcrypt is basically a dead project but there was not good alternative in PHP at that time. I'm considering to switch to openssl for ZF 3.x but we should continue to mantain the MCrypt extension for ZF 2.x, until we don't find security issue on it.
