### ISSUE TITLE
Introducing a password handler authored by @DASPRiD 

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-crypt#30]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/6925
User: @macnibblet
Created On: 2014-11-25T15:01:28Z
Updated At: 2015-03-06T17:03:50Z
Body
Whats left be done
- [ ] What key to use for the `Zend\Crypt\Password\HandlerManager` 
- [ ] Integrate the HandlerManager into the mvc service listener factory
- [ ] Documentation

---
### Comment

User: @weierophinney
Created On: 2014-11-25T15:06:17Z
Updated At: 2014-11-25T15:06:17Z
Body
Would love to see some description and rationale for the additions...

---
### Comment

User: @macnibblet
Created On: 2014-11-25T15:11:39Z
Updated At: 2014-11-25T15:11:39Z
Body
@weierophinney In short this component will help developers migrate their users passwords to more secure algorithms. 

---
### Comment

User: @ojhaujjwal
Created On: 2015-01-19T11:12:01Z
Updated At: 2015-01-19T11:12:01Z
Body
I like the overall idea. :+1: 

---
### Comment

User: @padraic
Created On: 2015-01-20T22:06:23Z
Updated At: 2015-01-20T22:06:23Z
Body
Note to monitor https://github.com/zendframework/zf2/pull/7141 which is effectively proposing a new default (a minor twist on plain bcrypt to preserve entropy from >72 byte passwords).

---
### Comment

User: @weierophinney
Created On: 2015-02-19T20:34:56Z
Updated At: 2015-02-19T20:34:56Z
Body
@macnibblet What remains to be done? Can this be ready for 2.4?

---
### Comment

User: @macnibblet
Created On: 2015-02-19T20:38:55Z
Updated At: 2015-02-19T20:38:55Z
Body
@weierophinney Everything that is listed in the task list, if i don't manage to look into it on sunday i'm doubtful that I will have time to finish it before the 2.4 release.

---
### Comment

User: @weierophinney
Created On: 2015-02-19T21:35:58Z
Updated At: 2015-02-19T21:35:58Z
Body
@macnibblet I'll give you until the end of the first week of March to get code ready. :)

---
### Comment

User: @malukenho
Created On: 2015-03-05T18:14:34Z
Updated At: 2015-03-05T18:14:34Z
Body
@macnibblet just to remember /cc @weierophinney 

---
### Comment

User: @moderndeveloperllc
Created On: 2015-03-06T16:25:31Z
Updated At: 2015-03-06T16:25:31Z
Body
@macnibblet I'm concerned that the MCF identifiers that you are using for SHA1 and MD5 are not the standard identifiers that are used in the standard Modular Crypt Format. `$1$` is standard for MD5. SHA1 is not 'standard' (mainly because it's not strong enough), but I have seen a few implementations that use `$sha1`. At least adding these to the checks with what you have will help developers who have to integrate with other languages that use the standard C `crypt()` library.

---
### Comment

User: @DASPRiD
Created On: 2015-03-06T16:29:49Z
Updated At: 2015-03-06T16:29:49Z
Body
@moderndeveloperllc do you have a reference for the $1$ marker? Apart from that I'd agree to use those instead. Also we may want to remove the "simple-" part from the classes. No clue why I had chosen those names.

---
### Comment

User: @moderndeveloperllc
Created On: 2015-03-06T17:03:50Z
Updated At: 2015-03-06T17:03:50Z
Body
@DASPRiD The `$1$` is from the [`crypt()` library docs](https://www.freebsd.org/cgi/man.cgi?query=crypt%283%29). It also lists `$5$` for SHA256 and `$6$` for SHA512 along with the $2$ series for bcrypt.

I might actually take back what I've said in my previous comment, because `$1$` usually refers to an md5 where you are storing the salt - kinda like: `$1$fauihdfaoihfad$caeioanceoi039rasi09`. The code in these files are looking for a plain - single round MD5 with nothing but the hashed value itself stored. In the real world, would these even have an MCF?

FYI, The best explanation/reference I found was with Python's [PassLib documentation](http://pythonhosted.org/passlib/modular_crypt_format.html). As far as I can tell, there is no "standard" in that there are no IEEE or RFC standards out there. Most links I've seen refer to the PassLib docs. For instance, in the [scrypt module I built](https://bitbucket.org/moderndeveloperllc/zf2-scrypt), I decided to use `$s0$` because the leading [Java scrypt library](https://github.com/wg/scrypt) used that.

---

**Comment by ezimuel** [comment]
@GeeH I'm closing this PR for inactivity.
