### ISSUE TITLE
Encrypt/Openssl Unset Difference

### ISSUE THREAD

**Issue by m1st0** [zendframework/zend-crypt#31]
Zend Framework 2.4.6-2.5.3, Zend\Filter\Encrypt\Openssl.php
I believe the unset should read `unset($options['compression']);` , lines 90-93.

```
if (array_key_exists('compression', $options)) {
    $this->setCompression($options['compression']);
    unset($options['compress']);
}
```

The code above I believe results in 'Undefined index: compression' later in code.  Current workaround is to use `...->setCompression($string)` .

**Comment by ezimuel** [comment]
@m1st0 please open the issue to [zendframework/zend-filter](https://github.com/zendframework/zend-filter), thanks!

**Comment by m1st0** [comment]
Sounds good. Thanks.

**Comment by m1st0** [comment]
Moved to zendframework/zend-filter.
