### ISSUE TITLE
Deprecated: Salt support is deprecated starting with PHP 7.0.0 in zend-crypt/src/Password/Bcrypt.php on line 146

### ISSUE THREAD

**Issue by flik** [zendframework/zend-crypt#59]
Deprecated: Salt support is deprecated starting with PHP 7.0.0 in zend-crypt/src/Password/Bcrypt.php on line 146

### Expected results

I do not want this warning of deprecated, This thing should be fixed. It is messing up json response

### Actual results

Deprecated: Salt support is deprecated starting with PHP 7.0.0 in zend-crypt/src/Password/Bcrypt.php on line 146

**Comment by froschdesign** [comment]
@flik 
> I do not want this warning of deprecated, This thing should be fixed. It is messing up json response

The salt is no longer needed and also decprected with version 7.0 of PHP. Remove the salt from the options and do not use the related methods.

See:

* https://docs.zendframework.com/zend-crypt/password/#bcrypt (see notice to version 3.0)
* http://php.net/manual/en/function.password-hash.php (see the warning message)

**Comment by Xerkus** [comment]
The point of deprecation errors is to warn about using functionality that should not be used.

There are only two options here: Stop using deprecated functionality or disable reporting for `E_USER_DEPRECATED` error.
